import { ApiProperty } from '@nestjs/swagger';
import { IsEnum, IsNotEmpty, IsNumberString, IsString } from 'class-validator';
import { TradeDirection } from '../constants/enums';
import { PULSE_SUPPORTED_DURATION_CODES } from '../constants/trade-config';

export class PlaceTradeDto {
  @ApiProperty({ example: 'BTC/USDT' })
  @IsString()
  @IsNotEmpty()
  symbol: string;

  @ApiProperty({ enum: TradeDirection, example: TradeDirection.LONG })
  @IsEnum(TradeDirection)
  direction: TradeDirection;

  @ApiProperty({ enum: PULSE_SUPPORTED_DURATION_CODES, example: '30S' })
  @IsString()
  @IsEnum(PULSE_SUPPORTED_DURATION_CODES)
  duration: (typeof PULSE_SUPPORTED_DURATION_CODES)[number];

  @ApiProperty({
    example: '100',
    description: 'Trade amount in TDX. String decimal to preserve precision.',
  })
  @IsNumberString()
  amount: string;

  @ApiProperty({
    example: 'client-req-uuid',
    description: 'Idempotency key generated by frontend',
  })
  @IsString()
  @IsNotEmpty()
  clientRequestId: string;
}
