// frontend/src/admin/screens/AdminSecuritySettingsScreen.tsx
//
// Admin Settings → Security → Two-Factor Authentication.
//
// Change-authenticator flow (never deletes the old factor first):
//   1. AAL2 session required (this route is behind the admin MFA gate).
//   2. Re-verify the CURRENT authenticator code.
//   3. Enroll a NEW Supabase TOTP factor and show its QR/manual key once.
//   4. Verify the NEW factor's code.
//   5. Only then remove the OLD factor (it stays active on any failure).
//
// The TOTP secret/QR is generated by Supabase for this browser session only and
// is never persisted, never sent to the TradeX backend and never logged.

import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import {
  AlertCircle,
  Check,
  Copy,
  KeyRound,
  RefreshCw,
  ShieldCheck,
  ShieldOff,
} from 'lucide-react';

import { Badge, Button } from '../../components/ui';
import { useAdminSecurity } from '../context/AdminSecurityContext';
import { AdminMfaService, type AdminMfaEnrollment } from '../services/adminMfa.service';

type ChangePhase = 'idle' | 'current-code' | 'new-enrollment';

function formatDateTime(value?: string | null): string {
  if (!value) return '—';
  const parsed = new Date(value);
  return Number.isNaN(parsed.getTime()) ? '—' : parsed.toLocaleString();
}

function qrToSrc(qr: string): string {
  const trimmed = qr.trim();
  if (trimmed.startsWith('data:image')) return trimmed;
  return `data:image/svg+xml;utf-8,${encodeURIComponent(trimmed)}`;
}

export default function AdminSecuritySettingsScreen() {
  const navigate = useNavigate();
  const { mfa, refresh, loading } = useAdminSecurity();

  const [phase, setPhase] = useState<ChangePhase>('idle');
  /** Whether the current-code step is confirming a change or a disable. */
  const [intent, setIntent] = useState<'change' | 'disable'>('change');
  const [currentCode, setCurrentCode] = useState('');
  const [newCode, setNewCode] = useState('');
  const [enrollment, setEnrollment] = useState<AdminMfaEnrollment | null>(null);
  const [busy, setBusy] = useState(false);
  const [copied, setCopied] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [notice, setNotice] = useState<string | null>(null);

  const verifiedFactor = useMemo(
    () => (mfa?.factors ?? []).find((f) => f.status === 'verified') ?? null,
    [mfa?.factors],
  );
  const pendingFactors = mfa?.pendingFactors ?? 0;

  const reset = useCallback(() => {
    setPhase('idle');
    setCurrentCode('');
    setNewCode('');
    setEnrollment(null);
    setError(null);
  }, []);

  // Enrollment material must not survive leaving this screen.
  useEffect(() => () => setEnrollment(null), []);

  const copyKey = useCallback(async () => {
    if (!enrollment) return;
    try {
      await navigator.clipboard.writeText(enrollment.secret);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch {
      setCopied(false);
    }
  }, [enrollment]);

  // ---- Step 2: re-verify the CURRENT authenticator before anything changes ----
  const submitCurrentCode = useCallback(async () => {
    if (!verifiedFactor) {
      setError('No verified authenticator found.');
      return;
    }
    if (currentCode.trim().length < 6) {
      setError('Enter the 6-digit code from your CURRENT authenticator.');
      return;
    }

    setBusy(true);
    setError(null);
    setNotice(null);
    try {
      const result = await AdminMfaService.verifyCode(verifiedFactor.id, currentCode);
      if (!result.ok) {
        await AdminMfaService.recordEvent({
          event: 'ADMIN_MFA_VERIFY_FAILED',
          factorId: verifiedFactor.id,
          result: 'change_current_code_failed',
        }).catch(() => undefined);
        setError(result.message ?? 'That code is not valid.');
        return;
      }

      // ---- Disable path: only after the CURRENT factor is confirmed ----
      if (intent === 'disable') {
        for (const factor of mfa?.factors ?? []) {
          await AdminMfaService.unenrollFactor(factor.id);
        }

        await AdminMfaService.recordEvent({
          event: 'ADMIN_MFA_DISABLE',
          factorId: verifiedFactor.id,
          factorCount: mfa?.factors.length ?? 1,
          result: 'disabled',
        }).catch(() => undefined);

        setCurrentCode('');
        setPhase('idle');
        setNotice(
          'Two-factor authentication disabled. Admin API access stays blocked until you enroll a new authenticator.',
        );
        await refresh();
        navigate('/admin/mfa/setup', { replace: true });
        return;
      }

      // Current factor confirmed. Only NOW may a new factor be enrolled — the
      // existing factor stays active until the new one is verified.
      const material = await AdminMfaService.startEnrollment(mfa?.factors.length ?? 1);
      setEnrollment(material);
      setCurrentCode('');
      setPhase('new-enrollment');
    } catch (err) {
      setError(AdminMfaService.getErrorMessage(err, 'Could not start authenticator change.'));
    } finally {
      setBusy(false);
    }
  }, [currentCode, intent, mfa?.factors, mfa?.factors.length, navigate, refresh, verifiedFactor]);

  // ---- Step 3/4: verify the NEW factor, only then remove the OLD one ----
  const submitNewCode = useCallback(async () => {
    if (!enrollment) return;
    if (newCode.trim().length < 6) {
      setError('Enter the 6-digit code from the NEW authenticator.');
      return;
    }

    setBusy(true);
    setError(null);
    try {
      const result = await AdminMfaService.verifyCode(enrollment.factorId, newCode);
      if (!result.ok) {
        // FAILURE PATH: the old factor is deliberately left untouched.
        await AdminMfaService.recordEvent({
          event: 'ADMIN_MFA_VERIFY_FAILED',
          factorId: enrollment.factorId,
          result: 'change_new_code_failed',
        }).catch(() => undefined);
        setError(
          result.message ??
            'The new authenticator could not be verified. Your existing authenticator is still active.',
        );
        return;
      }

      // The new factor is verified and this session is AAL2 — the old factor
      // is removed only after this point.
      let oldRemoved = false;
      if (verifiedFactor && verifiedFactor.id !== enrollment.factorId) {
        oldRemoved = await AdminMfaService.unenrollFactor(verifiedFactor.id);
      }

      await AdminMfaService.recordEvent({
        event: 'ADMIN_MFA_CHANGED',
        factorId: enrollment.factorId,
        factorCount: (mfa?.factors.length ?? 1) + 1,
        result: oldRemoved ? 'replaced' : 'added',
      }).catch(() => undefined);

      setEnrollment(null);
      setNewCode('');
      setPhase('idle');

      const status = await refresh();
      setNotice(
        status?.nextStep === 'ADMIN_DASHBOARD'
          ? oldRemoved
            ? 'Authenticator changed. Your new authenticator is now active and the previous one was removed.'
            : 'New authenticator verified. Remove the previous factor from your authenticator app if it is no longer needed.'
          : 'New authenticator verified. Please complete 2FA verification to continue.',
      );
    } catch (err) {
      setError(AdminMfaService.getErrorMessage(err, 'Could not complete the authenticator change.'));
    } finally {
      setBusy(false);
    }
  }, [enrollment, mfa?.factors.length, newCode, refresh, verifiedFactor]);

  const aal2 = mfa?.aal === 'aal2';
  const qrSrc = enrollment ? qrToSrc(enrollment.qrCode) : null;

  return (
    <div className="space-y-3">
      <section className="rounded-[16px] border border-[#292B33] bg-[#15161C] p-4">
        <div className="flex flex-wrap items-start justify-between gap-3">
          <div className="flex items-center gap-3">
            <div
              className="flex h-10 w-10 items-center justify-center rounded-xl"
              style={{ background: 'linear-gradient(135deg, #FF8F3D, #FF7A18)' }}
            >
              <ShieldCheck size={18} className="text-[#111217]" />
            </div>
            <div>
              <p className="text-sm font-black text-[#F5F5F7]">Two-Factor Authentication</p>
              <p className="text-[11px] text-[#A1A4AE]">
                Google Authenticator (TOTP) — required for every admin action.
              </p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <Badge variant={mfa?.enrolled ? 'success' : 'warning'}>
              {mfa?.enrolled ? 'Enabled' : 'Not enrolled'}
            </Badge>
            <Badge variant={aal2 ? 'success' : 'warning'}>{mfa?.aal ?? 'aal1'}</Badge>
            <Button
              variant="secondary"
              size="sm"
              className="h-8 px-2 text-[11px]"
              onClick={() => void refresh()}
              disabled={loading}
            >
              <RefreshCw size={12} className="mr-1" />
              Refresh
            </Button>
          </div>
        </div>

        {mfa?.supabaseLinked === false && (
          <div className="mt-3 rounded-xl border border-[#4A3A23] bg-[#241C10] px-3 py-2 text-xs font-semibold text-[#F59E0B]">
            This account has no linked Supabase identity, so 2FA cannot be managed here. Contact an
            operator.
          </div>
        )}
        {mfa?.lookupFailed && (
          <div className="mt-3 rounded-xl border border-[#4A3A23] bg-[#241C10] px-3 py-2 text-xs font-semibold text-[#F59E0B]">
            MFA status could not be read from Supabase Auth. Verify with an operator before making
            changes.
          </div>
        )}

        <div className="mt-3 grid grid-cols-2 gap-2 text-[11px] sm:grid-cols-4">
          <div className="rounded-xl border border-[#202229] bg-[#0E0E12] px-3 py-2">
            <p className="text-[#A1A4AE]">Session assurance</p>
            <p className="mt-0.5 font-black text-[#F5F5F7]">{mfa?.aal ?? '—'}</p>
          </div>
          <div className="rounded-xl border border-[#202229] bg-[#0E0E12] px-3 py-2">
            <p className="text-[#A1A4AE]">Verified factors</p>
            <p className="mt-0.5 font-black text-[#F5F5F7]">
              {(mfa?.factors ?? []).filter((f) => f.status === 'verified').length}
            </p>
          </div>
          <div className="rounded-xl border border-[#202229] bg-[#0E0E12] px-3 py-2">
            <p className="text-[#A1A4AE]">Pending factors</p>
            <p className="mt-0.5 font-black text-[#F5F5F7]">{pendingFactors}</p>
          </div>
          <div className="rounded-xl border border-[#202229] bg-[#0E0E12] px-3 py-2">
            <p className="text-[#A1A4AE]">Failed attempts</p>
            <p className="mt-0.5 font-black text-[#F5F5F7]">{mfa?.throttle.failedAttempts ?? 0}</p>
          </div>
        </div>

        {(mfa?.factors ?? []).length > 0 && (
          <div className="mt-3 space-y-1.5">
            {(mfa?.factors ?? []).map((factor) => (
              <div
                key={factor.id}
                className="flex flex-wrap items-center justify-between gap-2 rounded-xl border border-[#202229] bg-[#0E0E12] px-3 py-2"
              >
                <div className="min-w-0">
                  <p className="truncate text-xs font-bold text-[#F5F5F7]">
                    {factor.friendlyName ?? factor.type.toUpperCase()}
                  </p>
                  <p className="text-[10px] text-[#A1A4AE]">
                    Added {formatDateTime(factor.createdAt)}
                  </p>
                </div>
                <Badge variant={factor.status === 'verified' ? 'success' : 'warning'}>
                  {factor.status}
                </Badge>
              </div>
            ))}
          </div>
        )}

        {mfa?.throttle.blocked && (
          <div className="mt-3 rounded-xl border border-[#4A2323] bg-[#281313] px-3 py-2 text-xs font-semibold text-[#F87171]">
            Verification is temporarily locked after repeated invalid codes. Retry in{' '}
            {mfa.throttle.retryAfterSeconds}s.
          </div>
        )}
      </section>

      {notice && (
        <div className="flex items-start gap-2 rounded-xl border border-[#1E3A2A] bg-[#0F1D16] px-3 py-2.5 text-xs font-semibold text-[#86EFAC]">
          <Check size={15} className="mt-0.5 shrink-0" />
          <span>{notice}</span>
        </div>
      )}

      {error && (
        <div className="flex items-start gap-2 rounded-xl border border-[#4A2323] bg-[#281313] px-3 py-2.5 text-xs font-semibold text-[#F87171]">
          <AlertCircle size={15} className="mt-0.5 shrink-0" />
          <span>{error}</span>
        </div>
      )}

      <section className="rounded-[16px] border border-[#292B33] bg-[#15161C] p-4">
        <p className="text-xs font-black uppercase tracking-[0.08em] text-[#A1A4AE]">Actions</p>

        <div className="mt-3 space-y-2">
          <div className="flex flex-wrap items-center justify-between gap-2 rounded-xl border border-[#202229] bg-[#0E0E12] px-3 py-2.5">
            <div className="min-w-0">
              <p className="text-xs font-bold text-[#F5F5F7]">Change Authenticator</p>
              <p className="text-[11px] text-[#A1A4AE]">
                Requires your current code. The existing authenticator stays active until the new one
                is verified.
              </p>
            </div>
            <Button
              variant="secondary"
              size="sm"
              className="h-8 px-3 text-[11px]"
              disabled={busy || !aal2 || !verifiedFactor}
              onClick={() => {
                reset();
                setIntent('change');
                setPhase('current-code');
              }}
            >
              <KeyRound size={12} className="mr-1" />
              Change Authenticator
            </Button>
          </div>

          <div className="flex flex-wrap items-center justify-between gap-2 rounded-xl border border-[#202229] bg-[#0E0E12] px-3 py-2.5">
            <div className="min-w-0">
              <p className="text-xs font-bold text-[#F5F5F7]">Disable 2FA</p>
              <p className="text-[11px] text-[#A1A4AE]">
                Removing MFA immediately blocks all admin API access until you enroll a new
                authenticator. Lost your device? Use the operator recovery procedure instead.
              </p>
            </div>
            <Button
              variant="secondary"
              size="sm"
              className="h-8 px-3 text-[11px]"
              disabled={busy || !aal2}
              onClick={() => {
                reset();
                setIntent('disable');
                setPhase('current-code');
              }}
            >
              <ShieldOff size={12} className="mr-1" />
              Disable 2FA
            </Button>
          </div>
        </div>

        {!aal2 && (
          <div className="mt-3 rounded-xl border border-[#4A3A23] bg-[#241C10] px-3 py-2 text-xs font-semibold text-[#F59E0B]">
            Your session is not verified ({mfa?.aal ?? 'aal1'}). Change and disable are only allowed
            from a verified (aal2) session.
          </div>
        )}
      </section>

      {phase === 'current-code' && (
        <section className="rounded-[16px] border border-[#292B33] bg-[#15161C] p-4">
          <p className="text-xs font-black uppercase tracking-[0.08em] text-[#A1A4AE]">
            {intent === 'disable' ? 'Confirm with your current code' : 'Step 1 — verify current authenticator'}
          </p>
          <p className="mt-2 text-[11px] text-[#A1A4AE]">
            {intent === 'disable'
              ? 'Enter the 6-digit code from your current authenticator to disable 2FA. This cannot be undone without re-enrolling.'
              : 'Enter the 6-digit code from your CURRENT authenticator. Nothing changes until it is verified.'}
          </p>

          <input
            type="text"
            inputMode="numeric"
            autoComplete="one-time-code"
            maxLength={6}
            value={currentCode}
            onChange={(e) => setCurrentCode(e.target.value.replace(/\D/g, ''))}
            placeholder="123456"
            className="mt-3 w-full rounded-xl border border-[#292B33] bg-[#0E0E12] px-4 py-3 text-center text-lg font-black tracking-[0.3em] text-[#F5F5F7] outline-none placeholder:text-[#4F525C] focus:border-[#FF7A18]"
          />

          <div className="mt-3 flex gap-2">
            <Button
              variant="secondary"
              size="sm"
              className="h-9 flex-1 text-xs"
              disabled={busy}
              onClick={reset}
            >
              Cancel
            </Button>
            <Button
              size="sm"
              className="h-9 flex-1 text-xs"
              loading={busy}
              onClick={() => void submitCurrentCode()}
            >
              {intent === 'disable' ? 'Disable 2FA' : 'Continue'}
            </Button>
          </div>
        </section>
      )}

      {phase === 'new-enrollment' && enrollment && (
        <section className="rounded-[16px] border border-[#292B33] bg-[#15161C] p-4">
          <p className="text-xs font-black uppercase tracking-[0.08em] text-[#A1A4AE]">
            Step 2 — scan the new authenticator
          </p>

          <div className="mt-3 flex flex-col items-center rounded-xl border border-[#292B33] bg-[#0E0E12] p-4">
            {qrSrc ? (
              <img
                src={qrSrc}
                alt="New Google Authenticator setup QR code"
                className="h-[180px] w-[180px] rounded-xl bg-white p-2"
              />
            ) : null}

            <p className="mt-3 text-[11px] font-bold uppercase tracking-wider text-[#A1A4AE]">
              Manual setup key
            </p>
            <div className="mt-1.5 flex w-full items-center gap-2 rounded-xl border border-[#292B33] bg-[#15161C] px-3 py-2">
              <code className="min-w-0 flex-1 truncate text-center text-sm font-bold tracking-[0.18em] text-[#F5F5F7]">
                {enrollment.secret}
              </code>
              <button
                type="button"
                onClick={() => void copyKey()}
                className="rounded-lg p-1.5 text-[#A1A4AE] hover:text-[#F5F5F7]"
                aria-label="Copy setup key"
              >
                {copied ? <Check size={15} className="text-[#22C55E]" /> : <Copy size={15} />}
              </button>
            </div>
            <p className="mt-2 text-center text-[10px] text-[#70737E]">
              Shown once during setup. TradeX never stores this key. Your existing authenticator
              remains active until this new one is verified.
            </p>
          </div>

          <p className="mt-3 text-[11px] text-[#A1A4AE]">
            Step 3 — enter the 6-digit code from the NEW authenticator.
          </p>
          <input
            type="text"
            inputMode="numeric"
            autoComplete="one-time-code"
            maxLength={6}
            value={newCode}
            onChange={(e) => setNewCode(e.target.value.replace(/\D/g, ''))}
            placeholder="123456"
            className="mt-2 w-full rounded-xl border border-[#292B33] bg-[#0E0E12] px-4 py-3 text-center text-lg font-black tracking-[0.3em] text-[#F5F5F7] outline-none placeholder:text-[#4F525C] focus:border-[#FF7A18]"
          />

          <div className="mt-3 flex gap-2">
            <Button
              variant="secondary"
              size="sm"
              className="h-9 flex-1 text-xs"
              disabled={busy}
              onClick={reset}
            >
              Cancel
            </Button>
            <Button
              size="sm"
              className="h-9 flex-1 text-xs"
              loading={busy}
              onClick={() => void submitNewCode()}
            >
              Verify new authenticator
            </Button>
          </div>
        </section>
      )}

      <section className="rounded-[16px] border border-[#292B33] bg-[#15161C] p-4">
        <p className="text-xs font-black uppercase tracking-[0.08em] text-[#A1A4AE]">
          Lost your authenticator?
        </p>
        <p className="mt-2 text-[11px] text-[#A1A4AE]">
          There is no self-service reset. An operator must verify your identity out-of-band and run
          the server-side recovery procedure, which writes an ADMIN_MFA_RECOVERY audit event. The old
          secret is never recoverable.
        </p>
      </section>
    </div>
  );
}